### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by luwol03**
hello guys,
it took me a long time to figure out, that I have to install Umzug with the beta tag to use the documentation in the master branch. That's why I want this little description.

### CODE REVIEW

**Review by mmkal — APPROVED** [review]
Looks good - just a note, the beta version is likely going to change soon, so you may want to stick with v2 for the time being.

**Comment by luwol03** [comment]
What does you mean with going to change soon? Are there an other syntax in beta6?

**Comment by mmkal** [comment]
The usage will be slightly different in v3. Not sure yet which beta revision or timeline, but there will be some breaking changes. No functionality is going away, but some of the options will be simplified/consolidated.

**Comment by papb** [comment]
You can use `v3.0.0-beta.5`, but don't forget that there might be breaking changes between what you see in `v3.0.0-beta.5` and `v3.0.0-beta.6` (and the final `v3`)

**Pull request merged**
