### PR TITLE
fix: resolve esm file path issue and '<<cwd>>' (example tests) on windows

### PR DESCRIPTION
**Pull request by anikghosh256**
#676

### CODE REVIEW

**Comment by mmkal** [comment]
@anikghosh256 thanks. I'm going to try getting CI running on Windows on this PR to test, will be force-pushing some commits, hope that's alright.

**Comment by anikghosh256** [comment]
@mmkal I've tested the pkg.pr.new install command, and it's working perfectly on my end. You can go ahead with the minor version bump!

Note: I used the example from [umzug.mjs](https://github.com/sequelize/umzug/blob/main/examples/2-es-modules/umzug.mjs) .

**Comment by anikghosh256** [comment]
@mmkal waiting for version bump!!

**Comment by mmkal** [comment]
@anikghosh256 released as a patch bump since I think arguably this was just a windows bug.

**Pull request merged**
