### PR TITLE
cleanup

### LINKED ISSUE #168: Remove `babel-runtime` from dependencies
Apparently it's not used and it's just bloating installations.

### PR DESCRIPTION
**Pull request by SimonSchick**
**WARNING: HEAVILY OPINIONATED PR WITH BREAKING CHANGES AHEAD**

This PR cleans up and polishes the entire package, making only relatively few breaking changes.

Fixes #168

**Breaking changes**:
 - Removes native es6 module support (this should be done in the same manner as coffe-script etc.)
 - Node v6+ only
 - Drop support for sequelize v3 and below (should still work but removed tests)

Notable changes:
 - Use npm (it's actually decent now)
 - Updates **EVERYTHING**
 - Removed babel and gulp entirely
   - Using typescript and ts-node as build system instead
 - Removed all runtime dependencies except bluebird
 - Beefed up linting and applied:
   - "prefer-arrow-callback": "error",
    - "prefer-const": "error",
    - "arrow-body-style": ["error", "as-needed"],
 - Remove test cases for coffee-script
   - Rationale: This doesn't really add any value, anyone can use a custom resolver, this functionality is sufficiently tested

### CODE REVIEW

**Comment by SimonSchick** [comment]
@PascalPflaum any comments?

**Comment by PascalPflaum** [comment]
Hi @SimonSchick. I agree with most of your changes and the way how you did them. However I will not merge this PR at it is right now. I will spread the several changes you made to include simple improvements (updating dependencies, npm instead yarn, updated node versions, etc.) in the next minor release and to recheck bigger changes for the next major release.

Thanks for your contribution, a bigger cleanup was way overdue and on my list since I took responsibility for this package.

**Comment by SimonSchick** [comment]
That's fine with me, cherry-pick all you want.
I just wanted to contribute my personal fork so others can (potentially) benefit.

**Comment by SimonSchick** [comment]
Closing this PR but not deleting my branch as this will never be merged :)

**Pull request closed without merging**
